variables:
  REGISTRY_URL: registry.tc.egov.local
  DOCKER_DRIVER: overlay
  #NO_PROXY: "localhost,127.0.0.0,127.0.1.1,127.0.1.1,local.home"
  #HTTP_PROXY: "http://127.0.0.1:1234"
  #HTTPS_PROXY: "http://127.0.0.1:1234"
  IMAGE_TAG: $REGISTRY_URL/$CI_PROJECT_NAME:$CI_COMMIT_TAG

stages:
  - build

build:
  stage: build
  script:
    - |
      echo "$(date) Logitn in ${REGISTRY_URL} 🎈"
      docker login -u="${REG_LOGIN}" -p="${REG_PASS}" registry.tc.egov.local

      echo "$(date) Start build ☕"
      docker build \
        --build-arg HTTP_PROXY=${HTTP_PROXY} \
        --build-arg HTTPS_PROXY=${HTTPS_PROXY} \
        --build-arg NO_PROXY=${NO_PROXY} \
        --network=host \
        -t $IMAGE_TAG \
        -f Dockerfile .
      
      echo "$(date) Push into ${REGISTRY_URL}💭"
      docker push $IMAGE_TAG

  only:
  - tags
  tags:
    - native
